force-app/main/default/objects/Case/fields/Problem_Code__c.field-meta.xml
<CustomField>
    <fullName>Problem_Code__c</fullName>
    <label>Problem Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Request_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Receipts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activity Gains</fullName>
            </value>
            <value>
                <fullName>Enlisted NAVET/OSVET Strength Gain</fullName>
            </value>
            <value>
                <fullName>Enlisted Service Record</fullName>
            </value>
            <value>
                <fullName>Enlisted Strength Gain</fullName>
            </value>
            <value>
                <fullName>Enlisted to Officer Conversions (AC)</fullName>
            </value>
            <value>
                <fullName>ESO</fullName>
            </value>
            <value>
                <fullName>Extensions</fullName>
            </value>
            <value>
                <fullName>Leave</fullName>
            </value>
            <value>
                <fullName>MILPAY</fullName>
            </value>
            <value>
                <fullName>NAVPTO_Transportation</fullName>
            </value>
            <value>
                <fullName>Officer Strength Gain (AC)</fullName>
            </value>
            <value>
                <fullName>Reenlistments</fullName>
            </value>
            <value>
                <fullName>Reserves</fullName>
            </value>
            <value>
                <fullName>Retirements/Separations</fullName>
            </value>
            <value>
                <fullName>Students</fullName>
            </value>
            <value>
                <fullName>Transfers</fullName>
            </value>
            <value>
                <fullName>Transient</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Travel Advance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Routed_PSD__c.field-meta.xml
<CustomField>
    <fullName>Routed_PSD__c</fullName>
    <label>Routed PSD</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFLOAT EAST</fullName>
            </value>
            <value>
                <fullName>AFLOAT WEST</fullName>
            </value>
            <value>
                <fullName>ATSUGI</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>CHARLESTON</fullName>
            </value>
            <value>
                <fullName>DJIBOUTI (CSD OF BAHRAIN)</fullName>
            </value>
            <value>
                <fullName>EVERETT</fullName>
            </value>
            <value>
                <fullName>GREAT LAKES</fullName>
            </value>
            <value>
                <fullName>GUAM</fullName>
            </value>
            <value>
                <fullName>GUANTANAMO BAY</fullName>
            </value>
            <value>
                <fullName>JACKSONVILLE</fullName>
            </value>
            <value>
                <fullName>KITSAP</fullName>
            </value>
            <value>
                <fullName>LEMOORE</fullName>
            </value>
            <value>
                <fullName>MAYPORT</fullName>
            </value>
            <value>
                <fullName>MONTEREY</fullName>
            </value>
            <value>
                <fullName>NAPLES</fullName>
            </value>
            <value>
                <fullName>NEW LONDON</fullName>
            </value>
            <value>
                <fullName>NORTH ISLAND</fullName>
            </value>
            <value>
                <fullName>OCEANA</fullName>
            </value>
            <value>
                <fullName>OKINAWA</fullName>
            </value>
            <value>
                <fullName>PEARL HARBOR</fullName>
            </value>
            <value>
                <fullName>PENSACOLA</fullName>
            </value>
            <value>
                <fullName>ROTA</fullName>
            </value>
            <value>
                <fullName>SAN ANTONIO</fullName>
            </value>
            <value>
                <fullName>SAN DIEGO</fullName>
            </value>
            <value>
                <fullName>SASEBO</fullName>
            </value>
            <value>
                <fullName>SIGONELLA</fullName>
            </value>
            <value>
                <fullName>TPD MEMPHIS</fullName>
            </value>
            <value>
                <fullName>TSC GREAT LAKES</fullName>
            </value>
            <value>
                <fullName>TSC MEMPHIS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseListController.cls
public with sharing class CaseListController {
        @AuraEnabled(cacheable = true)

        public static List<Case> getCases(String sortBy, String sortDirection){
            String query = 'SELECT Id, CaseNumber, Subject, Request_Type__c, Problem_Code__c, Routed_PSD__c, CreatedDate, Effective_Date__c FROM Case';
        if ( sortBy != null && sortDirection != null ) {
           query += ' ORDER BY ' + sortBy + ' ' + sortDirection;
        }
        return Database.query(query);
        }
}